[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.4.1",
    "fastmcp>=2.14.3",
    "litellm>=1.80.16",
    "mcp>=1.25.0",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.1",
]
